# Generated by Django 5.0.1 on 2024-02-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50)),
                ('edad', models.IntegerField(max_length=20)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
