# Generated by Django 5.0.1 on 2024-02-02 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrasenagestor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos',
            name='edad',
        ),
    ]
